### ISSUE TITLE
Create new project screen

### ISSUE THREAD

**Issue by cbrzn** [HUMCOIN/Marketplace#6]
In this task we'd like to define good inputs so the user has a better UX and we store the right type of data.

This is the prototype that has been written so far for this screen:
<img width="1280" alt="Screenshot 2020-01-05 at 19 34 23" src="https://user-images.githubusercontent.com/21031138/71788676-6289a380-2ff2-11ea-80f8-56f54fa1837d.png">

We'd like to make sure that the inputs types are good:

- Statement: Text area input
- Region: Dropdown input - Maybe with the five continents? Or an [autocomplete](https://www.npmjs.com/package/react-bootstrap-typeahead) input? / Example [here](https://ericgio.github.io/react-bootstrap-typeahead/)
- SGDS: Dropdown input - Fill with these options https://www.notion.so/humcoin/Sustainable-Development-Goals-SDGs-53bfb104055e4995a579198411125e31 | Please @ashomah give access to @FabiolaLombardi and @namesty on this page
- Budget: Dollar input - Example [here](https://react-bootstrap.github.io/components/input-group/#input-group)
- Duration: Text input with days label
- Revenue - Dropdown input with types of revenue (Must be given to us)

Please give us feedback and confirm this is the desired data that we want to store
@dpastoresc @ashomah

**Comment by ashomah** [comment]
To be displayed on the project profile, and thus needing input fields:
- Title of project
- Implementer(s) (with link to their profile)
- Statement (short sentence, limited number of characters)
- SDGs, as colored bubbles if possible - should behave like tags for the projects
- Location (instead of Region), might be linked to a list
- Impact objectives (number of beneficiaries)
- Duration (in days)
- Investment Type (type of Smart Contract Model)
- Budget, with maybe a bar that get filled up to show how much is already funded - currency should be $ before the numbers and USD after, to avoid confusion

**Comment by cbrzn** [comment]
> Investment Type (type of Smart Contract Model)

With that, you mean these two types?

<img width="858" alt="Screenshot 2020-01-08 at 17 07 23" src="https://user-images.githubusercontent.com/21031138/72020239-58a5b180-3239-11ea-8101-3da4dd115def.png">

I thought we were going to use only the Project-based fund
@ashomah
